spring:
  application:
    name: content-service-api
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  datasource:
    initialization-mode: always
    platform: 'postgres'
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#    url: ${DB_URL}
    url : jdbc:postgresql://localhost:5432/musicappdemo
swagger:
  enabled: true
  host: localhost:8080
  path:

security:
  jwtSecret: ${JWT_SECRET}

