spring:
  application:
    name: youtubemusic
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  datasource:
    initialization-mode: always
    platform: 'postgres'
    username: postgres
    password: 2446
    url: jdbc:postgresql://localhost:5432/musicappdemo


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
swagger:
  enabled: true
  host: localhost:8080
  path:

security:
  jwtSecret: ${JWT_SECRET}

